import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "@/redux/provider";
import { useSelector } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SEP project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <Providers >
          {children}
          </Providers>
        </body>
      </html>
    </>
  );
}
